package {{PACKAGE}};

import net.fabricmc.api.ModInitializer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * {{MOD_NAME}} — generated by NexusCraft Studio.
 */
public class {{MOD_ID_CLASS}} implements ModInitializer {
    public static final String MOD_ID = "{{MOD_ID}}";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

    @Override
    public void onInitialize() {
        LOGGER.info("[{{MOD_NAME}}] initializing…");
        ModItems.initialize();
    }
}
