plugins {
    id 'fabric-loom' version '1.7-SNAPSHOT'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html for more information.
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    {{MAPPINGS_LINE}}
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    // Java target resolved from the selected Minecraft version.
    it.options.release = {{JAVA_RELEASE}}
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_{{JAVA_ENUM}}
    targetCompatibility = JavaVersion.VERSION_{{JAVA_ENUM}}
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}
