/**
 * VOXEL shaderpack generator.
 *
 * Emits an Iris/OptiFire-compatible shaderpack from a style preset:
 * `shaders/composite.vsh` + `shaders/composite.fsh` (a real composite
 * pass: exposure, tonemap, grading, threshold bloom, depth-based fog,
 * screen-space god rays, sky tint, vignette) plus the manifest and an
 * honest README. All GLSL here is original VOXEL code — tuned to
 * evoke iconic looks, never copied from third-party packs.
 */

import type { Rgb, ShaderStyle, ShaderStyleParams } from "./shaderStyleCatalog";
import { validateStyleParams } from "./shaderStyleCatalog";

export interface ShaderPackFile {
  path: string;
  content: string;
}

export interface GeneratedShaderPack {
  files: ShaderPackFile[];
  slug: string;
}

/** Formats a number as a GLSL float literal (always with a decimal point). */
function fmt(n: number): string {
  return n.toFixed(3);
}

function fmtRgb(rgb: Rgb): string {
  const [r, g, b] = rgb;
  return `vec3(${fmt(r / 255)}, ${fmt(g / 255)}, ${fmt(b / 255)})`;
}

export function slugifyPackName(name: string): string {
  const slug = name
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 64);
  if (!slug || /^-|-$/.test(slug)) {
    throw new Error("Pack name must contain letters or digits");
  }
  return slug;
}

function tonemapFunction(kind: ShaderStyleParams["tonemap"]): string {
  switch (kind) {
    case "aces":
      return [
        "// ACES filmic approximation (Narkowicz)",
        "vec3 ncTonemap(vec3 x) {",
        "    x *= 0.6;",
        "    float a = 2.51; float b = 0.03;",
        "    float c = 2.43; float d = 0.59; float e = 0.14;",
        "    return clamp((x * (a * x + b)) / (x * (c * x + d) + e), 0.0, 1.0);",
        "}",
      ].join("\n");
    case "reinhard":
      return [
        "// Reinhard-Jodie style curve",
        "vec3 ncTonemap(vec3 x) {",
        "    vec3 numerator = x * (vec3(1.0) + x);",
        "    vec3 denominator = vec3(1.0) + x * (1.0 + max(x - vec3(1.0), vec3(0.0)));",
        "    return clamp(numerator / denominator, 0.0, 1.0);",
        "}",
      ].join("\n");
    case "filmic":
      return [
        "// Uncharted-2 style filmic curve",
        "vec3 ncTonemap(vec3 x) {",
        "    x = max(vec3(0.0), x - vec3(0.004));",
        "    return (x * (6.2 * x + 0.5)) / (x * (6.2 * x + 1.7) + 0.06);",
        "}",
      ].join("\n");
    case "none":
      return [
        "// Linear clamp (no tonemap)",
        "vec3 ncTonemap(vec3 x) {",
        "    return clamp(x, 0.0, 1.0);",
        "}",
      ].join("\n");
  }
}

/** Deterministic 12-tap dual-ring bloom sample offsets. */
function bloomTaps(): string {
  const lines: string[] = [];
  for (let i = 0; i < 12; i++) {
    const angle = (i / 12) * Math.PI * 2;
    const radius = i < 6 ? 3.0 : 7.0;
    const x = Math.cos(angle) * radius;
    const y = Math.sin(angle) * radius;
    lines.push(
      `    bloom += ncBrightPass(texture2D(colortex0, uv + px * vec2(${fmt(x)}, ${fmt(y)})));`,
    );
  }
  return lines.join("\n");
}

const compositeVsh = `#version 120

// VOXEL Shader Studio — composite vertex pass (original code)
varying vec2 texcoord;

void main() {
    gl_Position = ftransform();
    texcoord = (gl_TextureMatrix[0] * gl_MultiTexCoord0).xy;
}
`;

function compositeFsh(style: ShaderStyle): string {
  const p = style.params;
  return `#version 120

// ============================================================
//  ${style.name} — generated by VOXEL Shader Studio
//  Style preset "${style.id}" · 100% original GLSL.
//  Not affiliated with the original "${style.name}" creators;
//  no third-party shader code is redistributed.
// ============================================================

uniform sampler2D colortex0;
uniform sampler2D depthtex0;
uniform float viewWidth;
uniform float viewHeight;
uniform float near;
uniform float far;
uniform vec3 sunPosition;
uniform mat4 gbufferProjection;

varying vec2 texcoord;

// ---- style parameters ----
#define NC_EXPOSURE ${fmt(p.exposure)}
#define NC_CONTRAST ${fmt(p.contrast)}
#define NC_SATURATION ${fmt(p.saturation)}
#define NC_VIBRANCE ${fmt(p.vibrance)}
#define NC_TEMPERATURE ${fmt(p.temperature)}
#define NC_BLOOM_STRENGTH ${fmt(p.bloomStrength)}
#define NC_BLOOM_THRESHOLD ${fmt(p.bloomThreshold)}
#define NC_GODRAYS ${fmt(p.godRays)}
#define NC_FOG_DENSITY ${fmt(p.fogDensity)}
#define NC_VIGNETTE ${fmt(p.vignette)}
#define NC_SKY_TOP ${fmtRgb(p.skyTop)}
#define NC_SKY_HORIZON ${fmtRgb(p.skyHorizon)}
#define NC_SUN_COLOR ${fmtRgb(p.sunColor)}

${tonemapFunction(p.tonemap)}

float ncLuma(vec3 c) {
    return dot(c, vec3(0.2126, 0.7152, 0.0722));
}

// Soft-knee bright pass feeding the bloom blur.
vec3 ncBrightPass(vec3 c) {
    float lum = ncLuma(c);
    float knee = NC_BLOOM_THRESHOLD + 0.2;
    float soft = clamp((lum - NC_BLOOM_THRESHOLD) / (knee - NC_BLOOM_THRESHOLD), 0.0, 1.0);
    soft = soft * soft;
    return c * soft;
}

// 12-tap dual-ring threshold blur (cheap, stable).
vec3 ncBloom(vec2 uv) {
    vec2 px = vec2(1.0 / viewWidth, 1.0 / viewHeight);
    vec3 bloom = vec3(0.0);
${bloomTaps()}
    return (bloom / 12.0) * NC_BLOOM_STRENGTH;
}

float ncLinearizeDepth(float d) {
    float z = d * 2.0 - 1.0;
    return (2.0 * near * far) / (far + near - z * (far - near));
}

// Screen-space sun shafts marching towards the projected sun.
vec3 ncGodRays(vec2 uv) {
    vec4 clip = gbufferProjection * vec4(normalize(sunPosition), 1.0);
    vec2 sunUv = clip.xy / clip.w * 0.5 + 0.5;
    if (sunUv.x < -0.2 || sunUv.x > 1.2 || sunUv.y < -0.2 || sunUv.y > 1.2) {
        return vec3(0.0);
    }
    vec2 step = (sunUv - uv) / 12.0;
    vec2 p = uv;
    float open = 0.0;
    for (int i = 0; i < 12; i++) {
        p += step;
        float d = texture2D(depthtex0, clamp(p, 0.0, 1.0)).r;
        open += (d >= 1.0) ? 0.0833 : 0.0;
    }
    float dist = length(sunUv - uv);
    float falloff = max(0.0, 1.0 - dist * 1.6);
    return NC_SUN_COLOR * open * falloff * falloff * NC_GODRAYS * 0.45;
}

void main() {
    vec3 color = texture2D(colortex0, texcoord).rgb;
    float depth = texture2D(depthtex0, texcoord).r;

    if (depth < 1.0) {
        // World geometry: distance fog tinted with the style horizon
        float dist = ncLinearizeDepth(depth);
        float fog = clamp(1.0 - exp(-NC_FOG_DENSITY * 0.004 * dist), 0.0, 0.9);
        color = mix(color, NC_SKY_HORIZON * (ncLuma(NC_SKY_HORIZON) + 0.35), fog);
    } else {
        // Sky: pull vanilla towards the style palette
        float horizon = clamp(texcoord.y * 1.4, 0.0, 1.0);
        vec3 tint = mix(NC_SKY_HORIZON, NC_SKY_TOP, horizon);
        color = mix(color, color * tint * 1.5, 0.3);
    }

    // Light accumulation before tonemapping
    color += ncBloom(texcoord) + ncGodRays(texcoord);

    // Exposure + tonemap
    color = ncTonemap(color * NC_EXPOSURE);

    // Contrast around gamma mid-gray
    color = (color - 0.18) * NC_CONTRAST + 0.18;

    // Saturation
    float lum = ncLuma(color);
    color = mix(vec3(lum), color, NC_SATURATION);

    // Vibrance: lifts muted tones more than saturated ones
    float sat = max(color.r, max(color.g, color.b)) - min(color.r, min(color.g, color.b));
    color = mix(vec3(lum), color, 1.0 + NC_VIBRANCE * (1.0 - sat) * 0.8);

    // Temperature: warm pushes red up / blue down, cool the reverse
    color += vec3(NC_TEMPERATURE, 0.0, -NC_TEMPERATURE) * 0.08;

    // Vignette
    vec2 vuv = texcoord - 0.5;
    color *= clamp(1.0 - NC_VIGNETTE * dot(vuv, vuv) * 2.0, 0.0, 1.0);

    gl_FragColor = vec4(clamp(color, 0.0, 1.0), 1.0);
}
`;
}

function shadersProperties(style: ShaderStyle): string {
  return [
    `# VOXEL Shader Studio — ${style.name}`,
    `# Style preset: ${style.id} (generated, 100% original GLSL)`,
    `# Original "${style.name}" by its own author: ${style.sourceUrl}`,
    "# Iris / OptiFine loads this shaderpack from shaders/ automatically.",
    "",
  ].join("\n");
}

function manifestJson(style: ShaderStyle, name: string, createdAt: string): string {
  return JSON.stringify(
    {
      name,
      styleId: style.id,
      createdAt,
      generator: "voxel",
      params: style.params,
    },
    null,
    2,
  );
}

function readmeTxt(style: ShaderStyle, name: string): string {
  return [
    `${name}`,
    `Generated by VOXEL Shader Studio — style preset "${style.name}".`,
    "",
    "This shaderpack is 100% original VOXEL-generated GLSL, tuned to",
    "evoke the look of an iconic community shaderpack. It is NOT the",
    "original and redistributes nothing from it.",
    "",
    `You can find the original "${style.name}" by its author here:`,
    style.sourceUrl,
    "",
    "INSTALL",
    "  1. Copy this folder into your instance's shaderpacks/ directory",
    "     (VOXEL: open the instance and use Shaders → Install).",
    "  2. In-game (Iris/OptiFine), open Shader Pack selection and pick",
    `     "${name}".`,
    "",
    "VOXEL is an independent third-party tool and is not",
    "affiliated with Mojang Studios or Microsoft.",
    "",
  ].join("\n");
}

/** Generates the complete shaderpack file set for a style preset. */
export function generateShaderPack(
  style: ShaderStyle,
  name: string,
  createdAt: string = new Date().toISOString(),
): GeneratedShaderPack {
  const errors = validateStyleParams(style.params);
  if (errors.length > 0) {
    throw new Error(`Invalid style params for "${style.id}": ${errors.join("; ")}`);
  }
  const slug = slugifyPackName(name);

  const files: ShaderPackFile[] = [
    { path: "shaders/composite.vsh", content: compositeVsh },
    { path: "shaders/composite.fsh", content: compositeFsh(style) },
    { path: "shaders.properties", content: shadersProperties(style) },
    { path: "voxel.json", content: manifestJson(style, name, createdAt) },
    { path: "README.txt", content: readmeTxt(style, name) },
  ];

  // No template tokens may survive generation
  for (const file of files) {
    if (file.content.includes("{{")) {
      throw new Error(`Unrendered template token in ${file.path}`);
    }
  }

  return { files, slug };
}
